### ISSUE TITLE
Dark mode snippet

### ISSUE THREAD

**Issue by smgabardo** [Nigecat/obsidian-desmos#104]
This block of code was _originally posted by @Nigecat in https://github.com/Nigecat/obsidian-desmos/issues/59#issuecomment-1123065429_

"The following css selectors should apply to all the current graph elements:
```css
/* Set the graph background colour */
.desmos-graph .dcg-svg-background {
    fill: #272f34;
}

/* Set gridline colour */
.desmos-graph .dcg-svg-minor-gridline {
    stroke: #ffffff; 
}

/* Set axis colour */
.desmos-graph .dcg-svg-axis-line {
    stroke: #ffffff;
}

/* Set axis text border colour (you probably want this to be the same as the graph background colour) */
.desmos-graph .dcg-svg-axis-value :nth-child(1) {
    stroke: #ff0000;
}

/* Set axis text colour */
.desmos-graph .dcg-svg-axis-value :nth-child(2) {
    stroke: #00ff00;
}

/* Set label text colour */
.desmos-graph .dcg-svg-label :nth-child(2) > * :nth-child(1) {
    fill: #ff0000;
}

/* Set label text border colour (you probably want this to be the same as the graph background colour) */
.desmos-graph .dcg-svg-label :nth-child(1) > * :nth-child(1) {
    stroke: #000000;
}
```
[...]"

However, when applying the following snippet, this is the result.
![image](https://user-images.githubusercontent.com/69433133/284725004-89a963e1-a055-472c-b02b-011fdb06fa55.png)

Is there a css snippet which does not make the Desmos window like this? Thanks!

**Comment by gojzdar** [comment]
Here is my version of the snippet.
The snippet you are using is intentionally ugly, so you can quickly find the colors you want to change.
I did that and arrived at my (slightly modified) snippet. I also added `.theme-dark` rules which only apply when you are using the dark theme.

```
/* https://github.com/Nigecat/obsidian-desmos/issues/59#issuecomment-1123065429 */

/* Set the graph background colour */
.desmos-graph .dcg-svg-background {
     fill: var(--background-primary);
}

/* Set gridline colour */
.theme-dark .desmos-graph .dcg-svg-minor-gridline {
    stroke: #ffffff;
}

/* Set axis colour */
.theme-dark .desmos-graph .dcg-svg-axis-line {
    stroke: #ffffff;
}

/* Set axis text border colour (you probably want this to be the same as the graph background colour) */
.theme-dark .desmos-graph .dcg-svg-axis-value :nth-child(1) {
    stroke-width: 0;
}

/* Set axis text colour */

.theme-dark .desmos-graph .dcg-svg-axis-value :nth-child(2) {
    stroke: #ccc;
}

/* Set label text colour */
.desmos-graph .dcg-svg-label :nth-child(2) > * :nth-child(1) {
    /* fill: var(--text-accent); */
    stroke: transparent;
}

/* Set label text border colour (you probably want this to be the same as the graph background colour) */
.theme-dark .desmos-graph .dcg-svg-label :nth-child(1) > * :nth-child(1) {
    stroke-width: 0;
}
```

**Comment by gojzdar** [comment]
For reference, here is how it looks for me:
![image](https://github.com/Nigecat/obsidian-desmos/assets/135328910/9f3d8fa2-ae84-449e-8bec-07e41b184835)

**Comment by gojzdar** [comment]
However, after you modify, or even look at the graph source, the HTML changes.

[before.txt](https://github.com/Nigecat/obsidian-desmos/files/13805424/before.txt)
[after.txt](https://github.com/Nigecat/obsidian-desmos/files/13805423/after.txt)

**Comment by kamyker** [comment]
+1 css breaks all the time

**Comment by mattchew1010** [comment]
I was having problems with the parenthesis of the point labels having a white stroke despite the inside text having none. Heres a fix for that if anyone has the same problem:
```css
.desmos-graph .dcg-svg-label :nth-child(n)>* :nth-child(1) {
	stroke: none;
}
```
