### ISSUE TITLE
CSS graph styling stops working after viewing graph codeblock as text

### ISSUE THREAD

**Issue by gojzdar** [Nigecat/obsidian-desmos#109]
I used this snippet, from [link](https://github.com/Nigecat/obsidian-desmos/issues/59#issuecomment-1123065429). It works fine, until you move inside the codeblock by clicking on the "edit this block" button.

According to my very short investigations, the HTML code changes (the hash changed), which somehow breaks the styling.

```css
/* Set the graph background colour */
.desmos-graph .dcg-svg-background {
    fill: #272f34;
}

/* Set gridline colour */
.desmos-graph .dcg-svg-minor-gridline {
    stroke: #ffffff; 
}

/* Set axis colour */
.desmos-graph .dcg-svg-axis-line {
    stroke: #ffffff;
}

/* Set axis text border colour (you probably want this to be the same as the graph background colour) */
.desmos-graph .dcg-svg-axis-value :nth-child(1) {
    stroke: #ff0000;
}

/* Set axis text colour */
.desmos-graph .dcg-svg-axis-value :nth-child(2) {
    stroke: #00ff00;
}

/* Set label text colour */
.desmos-graph .dcg-svg-label :nth-child(2) > * :nth-child(1) {
    fill: #ff0000;
}

/* Set label text border colour (you probably want this to be the same as the graph background colour) */
.desmos-graph .dcg-svg-label :nth-child(1) > * :nth-child(1) {
    stroke: #000000;
}
```

Alternatively, if you want to inherit it from your css theme the variables can be read directly (the specific variables used may need to be tweaked depending on your theme, these work for my theme but looks a bit off with the default theme):
```css
/* Set the graph background colour */
.desmos-graph .dcg-svg-background {
    fill: var(--background-primary);
}

/* Set gridline colour */
.desmos-graph .dcg-svg-minor-gridline {
    stroke: var(--background-modifier-border); 
}

/* Set axis colour */
.desmos-graph .dcg-svg-axis-line {
    stroke: var(--background-accent); 
}

/* Set axis text border colour */
.desmos-graph .dcg-svg-axis-value :nth-child(1) {
    stroke: var(--background-primary);
}

/* Set axis text colour */
.desmos-graph .dcg-svg-axis-value :nth-child(2) {
    stroke: var(--text-accent);
}

/* Set label text colour */
.desmos-graph .dcg-svg-label :nth-child(2) > * :nth-child(1) {
    stroke: var(--text-accent);
}

/* Set label text border colour */
.desmos-graph .dcg-svg-label :nth-child(1) > * :nth-child(1) {
    stroke: var(--background-primary);
}
```

_Originally posted by @Nigecat in https://github.com/Nigecat/obsidian-desmos/issues/59#issuecomment-1123065429_

**Comment by AlanMatiusevskij** [comment]
Having a similar problem.
I'm clueless to obsidian backend and css, so I don't know how to investigate.

When I start obsidian and load the desmos graph for the first time, the theme does apply. Then I switch to another note where another desmos graph loads in and it's theme is also applied properly. 
However, if i go back to the previous note, it tries to, perhaps, render again and fails to apply the theme values. This happens to all second-time-loaded graphs.

Currently on Arch Linux and obsidian was installed from pacman package manager.

**Comment by RunTheBot** [comment]
remove the `.desmos-graph` for some reason it causes the CSS to stop matching. This is not a problem with this plugin or obsidian.

**Comment by RunTheBot** [comment]
```css
/* Set the graph background colour */
.dcg-svg-background {
    fill: var(--background-primary);
}

/* Set gridline colour */
.dcg-svg-minor-gridline {
    stroke: var(--background-modifier-border); 
}

/* Set axis colour */
.dcg-svg-axis-line {
    stroke: var(--background-secondary); 
    stroke-width: 3;
    stroke-opacity: 1;
}

/* Set axis text border colour */
.dcg-svg-axis-value :nth-child(1) {
    stroke: var(--background-primary);
}

/* Set axis text colour */
.dcg-svg-axis-value :nth-child(2) {
    stroke: var(--text-accent);
}

/* Set label text colour */
.dcg-svg-label :nth-child(2) > * :nth-child(1) {
    stroke: var(--text-accent);
}

/* Set label text border colour */
.dcg-svg-label :nth-child(1) > * :nth-child(1) {
    stroke: var(--background-primary);
}
```
