### ISSUE TITLE
Scrollable graph

### ISSUE THREAD

**Issue by ShahriarKh** [Nigecat/obsidian-desmos#83]
I played with CSS and JS and improved the graph display. Now, the graph won't go out of bounds, and is scrollable.
Here's the CSS:
```css
.block-language-desmos-graph {
   max-width: 100%;
   max-height: 300px; /* optional */
   overflow: auto;
   cursor: grab;
}

/* to center-align the graph when it's narrower than the editor */
.block-language-desmos-graph svg {
   display: block;
   margin-left: auto;
   margin-right: auto;
}
```
and JS (thanks to [ToddWebDev](https://codepen.io/toddwebdev/pen/yExKoj) and [Lachlan](https://codepen.io/loxks/pen/KKpVvVW)):
```js
const slider = document.querySelector('.block-language-desmos-graph');
let isDown = false;
let startX, startY, scrollLeft, scrollTop;
let scrollSpeed = 1; // 2 or 3 for large graphs. This can be a dynamic value, based on the size of the graph

/* set to center of the graph by default */
slider.scrollLeft =  (slider.scrollWidth - slider.clientWidth ) / 2;
slider.scrollTop =  (slider.scrollHeight - slider.clientHeight ) / 2;

slider.addEventListener('mousedown', (e) => {
  isDown = true;
  slider.style.cursor = 'grabbing';
  startX = e.pageX - slider.offsetLeft;
  startY = e.pageY - slider.offsetTop;
  scrollLeft = slider.scrollLeft;
  scrollTop = slider.scrollTop;
  cancelMomentumTracking();
});

slider.addEventListener('mouseleave', () => {
  isDown = false;
  slider.style.cursor = 'grab';
});

slider.addEventListener('mouseup', () => {
  isDown = false;
  slider.style.cursor = 'grab';
  beginMomentumTracking();
});

slider.addEventListener('mousemove', (e) => {
  if(!isDown) return;
  e.preventDefault();
  const x = e.pageX - slider.offsetLeft;
  const y = e.pageY - slider.offsetTop;
  var prevScrollLeft = slider.scrollLeft;
  var prevScrollTop = slider.scrollTop;
  const walk = (x - startX) * scrollSpeed;
  const jump = (y - startY) * scrollSpeed;
  slider.scrollLeft = scrollLeft - walk;
  slider.scrollTop = scrollTop - jump;
  velX = slider.scrollLeft - prevScrollLeft;
  velY = slider.scrollTop - prevScrollTop;
});

/* for smooth scrolling */
var velX = 0;
var momentumID;

slider.addEventListener('wheel', (e) => {
  cancelMomentumTracking();
});  

function beginMomentumTracking(){
  cancelMomentumTracking();
  momentumID = requestAnimationFrame(momentumLoop);
}
function cancelMomentumTracking(){
  cancelAnimationFrame(momentumID);
}
function momentumLoop(){
  slider.scrollLeft += velX;
  velX *= 0.95; 
  if (Math.abs(velX) > 0.5){
    momentumID = requestAnimationFrame(momentumLoop);
  }
}
```
